name: okapi_dart
description: Dart language bindings for okapi
version: 1.0.0
# homepage:

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  protobuf: ^2.0.1
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
